export const PAGES = {
    ACCOUNT: 'account',
    ACCOUNT_EDIT: 'account-edit',
    BECOME_DEALER: 'become-dealer',
    BRAND: 'brand',
    CAR: 'car',
    CAREER_DETAIL: 'career-detail',
    CAREERS: 'careers',
    CARS: 'cars',
    COLAB: 'colab',
    COMPANY: 'company',
    CONTACT: 'contact',
    COOKIES: 'cookies',
    EVENT_DETAIL: 'event-detail',
    FORGOT_PASSWORD: 'forgot-password',
    HOME: 'home',
    LOGIN: 'login',
    PRESS: 'press',
    NEWS_EVENTS: 'news-events',
    NEWS_ITEM: 'news-item',
    PRIVACY: 'privacy-policy',
    PROJECT: 'project',
    REGISTER: 'register',
    SECTION: 'section',
    NOT_FOUND: '404',
    ERROR: '500',
};

export const PAGES_CLASSES = {
    ACCOUNT_EDIT: 'page-edit',
    ACCOUNT: 'page-account-info',
    BECOME_DEALER: 'page-dealer',
    BRAND: 'page-brand',
    CAR: 'page-car',
    CAREER_DETAIL: 'page-careers-detail',
    CAREERS: 'page-careers',
    CARS: 'page-cars',
    COLAB: 'page-colab',
    COMPANY: 'page-company',
    CONTACT: 'page-contact',
    COOKIES: 'page-cookies',
    EVENT_DETAIL: 'page-event',
    FORGOT_PASSWORD: 'page-forgot-password',
    HOME: 'page-home',
    LOGIN: 'page-login',
    NEWS_EVENTS: 'page-news-events',
    NEWS_ITEM: 'page-news-item',
    PRESS: 'page-press',
    PRIVACY: 'page-privacy',
    PROJECT: 'page-project',
    REGISTER: 'page-register',
    SECTION: 'page-section',
    NOT_FOUND: 'page-error',
    ERROR: 'page-error',
};
