export const PATHS = {
    HOMEPAGE: '/',
    BRAND: '/brand',
    CARS: '/cars',
    COLAB: '/colab',
    PROJECT: '/projects/:id',
    // PROJECT_CMS: '/projects/*',
    PRESS: '/press',
    NEWS_EVENTS: '/news-events',
    NEWS_ITEM: '/news/:id',
    // NEWS_ITEM_CMS: '/news/*',
    EVENT: '/events/:id',
    // EVENT_CMS: '/events/*',
    CAREERS: '/careers',
    CAREER_DETAIL: '/careers/:id',
    CONTACT: '/contact',
    BECOME_DEALER: '/become-dealer',
    REGISTER: '/register',
    LOGIN: '/login',
    ACCOUNT: '/my-account',
    ACCOUNT_EDIT: '/my-account/edit',
    ACCOUNT_EVENTS: '/my-account/events',
    ACCOUNT_PROJECTS: '/my-account/projects',
    FORGOT_PASSWORD: '/forgot-password',
    PRIVACY: '/privacy-policy',
    COMPANY: '/company',
    COOKIES: '/cookies',
    SECTIONS: '/sections',
    NOT_FOUND: '/404',
    ERROR: '/500',
    ZH_CN: 'zh_cn',
    EN: 'en',
};